name: develop pull request Check and Test

on:
  pull_request:
    branches: [ "develop" ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DB_NAME: ${{ secrets.DATABASE_NAME }}
      DB_USERNAME: ${{ secrets.DATABASE_USERNAME }}
      DB_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}

    strategy:
      matrix:
        java-version: [ 17 ]
        distribution: [ 'temurin' ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-version }}
          distribution: ${{ matrix.distribution }}

      - name: Run MySQL with Docker
        run: |
          docker run -d \
          --name mysql \
          -e MYSQL_ROOT_PASSWORD=$DB_PASSWORD \
          -e MYSQL_DATABASE=$DB_NAME \
          -p 3306:3306 \
          mysql:8.0

      - name: Run Redis with Docker
        run: |
          docker run -d \
          --name redis \
          -p 6379:6379 \
          redis:7.0

      - name: Grant Execute Permission for Gradlew
        run: chmod +x ./gradlew

      - name: Run Gradle Check
        run: ./gradlew check

      # 슬랙으로 알림 전송
      - name: Send to slack notification
        uses: slackapi/slack-github-action@v2.1.0
        with:
          method: chat.postMessage
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            channel: ${{ secrets.SLACK_CHANNEL_ID }}
            text: "PR event"
            blocks: 
              - type: section
                text:
                  type: mrkdwn
                  text: "${{ secrets.SLACK_GROUP_MENTION }}\n\n📌 *PR 이벤트 알림 (<${{ github.event.pull_request.html_url }}|#${{ github.event.pull_request.number }}>)*"
              - type: section
                text:
                  type: mrkdwn
                  text: "> PR 이벤트 알림입니다.\n> *최신 변경 사항 검토*, *코드 리뷰* 부탁드립니다."
              - type: section
                text:
                  type: mrkdwn
                  text: "*PR:* 🔗 <${{ github.event.pull_request.html_url }}|${{ github.event.pull_request.title }}>"
              - type: context
                elements:
                  - type: mrkdwn
                    text: "*브랜치:* `${{ github.head_ref }}` -> `${{ github.base_ref }}`"
                  - type: mrkdwn
                    text: "*작성자:* ${{ github.event.pull_request.user.login }}"
              - type: divider
